export const affiliationsMap = {
    "(finger)": 'Dedos',
    "Anastasia Camp": 'Acampamento Anastasia',
    "Arlam Village":'Aldeia Arlam',
    "Balleroy Temeglyph": 'Balleroy Temeglyph',
    "Banan": 'Banan',
    "Black Silver Coin": 'Moeda Prata Negra',
    "Capella Emerada Lugunica": 'Capella Emerada Lugunica',
    "Carnattse": 'Carnattse',
    "Chamber Of Commerce": 'Câmara de Comércio',
    "Chaosflame": 'Chama do Caos',
    "Commerce Guild":'Guilda de Comércio',
    "Costuul":'Costuul',
    "Council Of Ten": 'Conselho dos Dez',
    "Council Of Wise Men":'Conselho dos Sábios',
    "Crimson Hunting Party": 'Grupo de Caça Carmesim',
    "Crusch Camp": 'Acampamento Crusch',
    "Demi-human Alliance": 'Aliança Demi-humana',
    "Dias Fatsbalm": 'Dias Fatsbalm',
    "Disciplinary Unit":'Unidade Disciplinar',
    "Divine Dragon Church": 'Igreja do Dragão Divino',
    "Elf Village": 'Aldeia dos Elfos',
    "Elior Forest": 'Floresta Elior',
    "Emilia Camp": 'Acampamento Emilia',
    "Featherrun Sisters": 'Irmãs Featherrun',
    "Felt": 'Felt',
    "Felt Camp": 'Acampamento Felt',
    "Flanders": 'Flanders',
    "Flower Prison Garden": 'Jardim da Prisão das Flores',
    "Flugel": 'Flugel',
    "Flying Dragon Squadron": 'Esquadrão do Dragão Voador',
    "Garkla": 'Garkla',
    "Ginunhive": 'Ginunhive',
    "Glarasia": 'Glarasia',
    "Golden Wing Faction": 'Facção Asa Dourada',
    "Grimour Prison": 'Prisão Grimour',
    "Guineb": 'Guineb',
    "Gustekan Church":'Igreja Gustekan',
    "Gusteko": 'Gusteko',
    "Hakuchuri": 'Hakuchuri',
    "Halibel Camp": 'Acampamento Halibel',
    "Hartgeny": 'Hartgeny',
    "Heliopolis": 'Heliopolis',
    "House Argyle": 'Casa Argyle',
    "House Astrea": 'Casa Astrea',
    "House Barielle": 'Casa Barielle',
    "House Dracroy": 'Casa Dracroy',
    "House Edditz": 'Casa Edditz',
    "House Endymion": 'Casa Endymion',
    "House Godwin": 'Casa Godwin',
    "House Goldario": 'Casa Goldario',
    "House Hoffman": 'Casa Hoffman',
    "House Iglesia": 'Casa Iglesia',
    "House Juukulius": 'Casa Juukulius',
    "House Karsten": 'Casa Karsten',
    "House Mathers": 'Casa Mathers',
    "House Mcmahon": 'Casa Mcmahon',
    "House Miload": 'Casa Miload',
    "House Peitiet": 'Casa Peitiet',
    "House Pendleton": 'Casa Pendleton',
    "House Remendis": 'Casa Remendis',
    "Ice Thieves": 'Ladrões de Gelo',
    "Imperial Army": 'Exército Imperial',
    "Imperial Armynine Divine Generals": 'Nove Generais Divinos do Exército Imperial',
    "Imperial Selection Ceremony": 'Cerimônia de Seleção Imperial',
    "Irlam Village": 'Aldeia Irlam',
    "Iron Fang": 'Presas de Ferro',
    "Ivada":'Ivada',
    "Japan": 'Japão',
    "Julius Juukulius":'Julius Juukulius',
    "Kararagi": 'Kararagi',
    "Kingdom Knights": 'Cavaleiros do Reino',
    "Kingdom Of Lugunica": 'Reino de Lugunica',
    "Kiritaka Muse": 'Muse Kiritaka',
    "League Of Cities": 'Liga das Cidades',
    "Leanotte": 'Leanotte',
    "Lupugana": 'Lupugana',
    "Madara Squadron": 'Esquadrão Madara',
    "Melty Camp": 'Acampamento Melty',
    "Muse Company": 'Companhia Muse',
    "Natsuki Subaru": 'Natsuki Subaru',
    "Nobility": 'Nobreza',
    "Omega Party": 'Grupo Ômega',
    "Otto Suwen": 'Otto Suwen',
    "Pappelt": 'Pappelt',
    "People Of Shudrak": 'Povo de Shudrak',
    "Picoutatte": 'Picoutatte',
    "Pleiades Watchtower": 'Torre de Vigia das Plêiades',
    "Priestella": 'Priestella',
    "Priscilla Camp": 'Acampamento Priscilla',
    "Razcrew Company": 'Companhia Razcrew',
    "Reid Astrea": 'Reid Astrea',
    "Rodriguez": 'Rodriguez',
    "Roswaal L. Mathers": 'Roswaal L. Mathers',
    "Royal Army": 'Exército Real',
    "Royal Armyroyal Guard": 'Exército Real/Guarda Real',
    "Royal Capital": 'Capital Real',
    "Royal Family": 'Família Real',
    "Royal Guard": 'Guarda Real',
    "Sanctuary": 'Santuário',
    "Scratch Of Silver": 'Arranhão de Prata',
    "Silver Shield": 'Escudo de Prata',
    "Six Tongues": 'Seis Línguas',
    "Spiritfour Great Spirits": 'Quatro Grandes Espíritos',
    "Stride Faction": 'Facção Stride',
    "Stride Vollachia": 'Stride Vollachia',
    "Suwen Company": 'Companhia Suwen',
    "Suwen Treatment Center": 'Centro de Tratamento Suwen',
    "The Balance": 'O Equilíbrio',
    "The Brotherhood": 'A Irmandade',
    "Unnamed Country": 'País Sem Nome',
    "Volcanica": 'Volcânica',
    "Vollachia Empire": 'Império Vollachia',
    "Vollachia Shinobi Village": 'Aldeia Shinobi Vollachia',
    "White Dragon's Scales": 'Escamas do Dragão Branco',
    "Witch Cult": 'Culto das Bruxas',
    "Witches Of Sin": 'Bruxas do Pecado',
    "Witchwitches Of Sin": 'Bruxas do Pecado',
    "Wolf Person Village": 'Aldeia dos Homens-Lobo',
    "Zergev Squadron":' Esquadrão Zergev' 
};