export const racesMap = {
    "":'Desconhecido',
    "Spirit": "Espírito",
    "Artificial Spirit": "Espírito Artificial",
    "Human": "Humano",
    "Bat Human": "Homem-Morcego",
    "Bear Human": "Homem-Urso",
    "Beast Human": "Homem-Fera",
    "Beast Human/leopard Human And Human Hybrid": "Homem-Fera (Híbrido de Leopardo e Humano)",
    "Beast Human/lion Human And Human Hybrid": "Homem-Fera (Híbrido de Leão e Humano)",
    "Beast Human/tiger Human And Human Hybrid": "Homem-Fera (Híbrido de Tigre e Humano)",
    "Beast Human/wolf Human And Human Hybrid": "Homem-Fera (Híbrido de Lobo e Humano)",
    "Cyclops Tribe": "Tribo dos Ciclopes",
    "Deer Human": "Homem-Cervo",
    "Demi-human/lizard Human Subspecies": "Demi-humano (Subespécie de Homem-Lagarto)",
    "Dog Human": "Homem-Cão",
    "Dragon": "Dragão",
    "Dragonkin": "Dragonkin",
    "Dwarf": "Anão",
    "Earth Dragon": "Dragão Terrestre",
    "Elf": "Elfo",
    "Elf/phantom": "Elfo/Fantasma",
    "Espírito": "Espírito",
    "Evil Eye Tribe": "Tribo do Olho Maligno",
    "Evil Eye Tribe/human Hybrid": "Híbrido de Humano e Tribo do Olho Maligno",
    "Flying Dragon": "Dragão Voador",
    "Fox Human": "Homem-Raposa",
    "Giant": "Gigante",
    "Half-elf": "Meio-Elfo",
    "Half-oni": "Meio-Oni",
    "Human/half-elf (formerly)": "Humano/Meio-Elfo (anteriormente)",
    "Human/phantom": "Humano/Fantasma",
    "Humano": "Humano",
    "Hyena Human": "Homem-Hiena",
    "Insect Cage Clan": "Clã da Gaiola de Insetos",
    "Kitten Human": "Homem-Gato (Filhote)",
    "Lizard Human": "Homem-Lagarto",
    "Meteor": "Meteoro (Constructo)",
    "Mole Human": "Homem-Toupeira",
    "Multi-arm Clan": "Clã de Múltiplos Braços",
    "Oni": "Oni",
    "Pig Human": "Homem-Porco",
    "Puppy Human": "Homem-Cão (Filhote)",
    "Rabbit Human": "Homem-Coelho",
    "Snake Human": "Homem-Serpente",
    "Steel Human": "Homem de Aço",
    "Tanuki Human": "Homem-Tanuki",
    "Weaponkin": "Weaponkin",
    "Werewolf/wolf Human And Human Hybrid": "Lobisomem (Híbrido de Homem-Lobo e Humano)",
    "Witchbeast": "Maju (Besta da Bruxa)",
    "Wolf Human": "Homem-Lobo"
};